Hw10 program optimization
technobulka/home_work pull request #10
Opened 2021-03-27 19:55 UTC by technobulka

## Домашнее задание №10 «Оптимизация программы»

### Критерии оценки
- [ ] Пайплайн зелёный и нет попытки «обмануть» систему - 4 балла
- [ ] Добавлены юнит-тесты - до 3 баллов
- [ ] Понятность и чистота кода - до 3 баллов

#### Зачёт от 7 баллов

2021-03-29 15:29 UTC, agneum requested changes
Спасибо за вариант решения. 
Хорошая работа, однако решение работает не во всех случаях (см. частые ошибки)

Итого: 6 баллов из 10

2021-03-29 15:29 UTC, agneum commented on hw10_program_optimization/stats.go
> +		etIdx = strings.Index(userLine, "@")
Если `Name` или `Username` содержат `@`, подсчёт доменов вернёт неправильный результат. 
Хотелось бы иметь гарантии того, что работа происходит именно с полем email. (см. [частые ошибки](https://github.com/technobulka/home_work/tree/hw10_program_optimization/hw10_program_optimization#%D1%87%D0%B0%D1%81%D1%82%D1%8B%D0%B5-%D0%BE%D1%88%D0%B8%D0%B1%D0%BA%D0%B8))
Предлагаю использовать оптимизированные json-парсеры(jsoniter, easyjson, и др.)

2021-03-30 13:11 UTC, technobulka commented on hw10_program_optimization/stats.go
> +		etIdx = strings.Index(userLine, "@")
поправил. еле уложился в тест, на локалке отрабатывает за 212мс

2021-03-31 11:17 UTC, agneum approved these changes
Спасибо за правки. Хорошая работа
Итого: 9 баллов из 10

2021-03-31 11:17 UTC, agneum commented on hw10_program_optimization/stats.go
> +	Address  string `json:"-"`
Думаю, что можно указать только нужное поле

2021-03-31 11:17 UTC, agneum commented on hw10_program_optimization/stats.go
> +			result[strings.ToLower(strings.SplitN(user.Email, "@", 2)[1])]++
Если email не сожержит `@`, будет паника при обращении ко второму элементу слайса

2021-04-01 18:58 UTC, technobulka commented on hw10_program_optimization/stats.go
> +			result[strings.ToLower(strings.SplitN(user.Email, "@", 2)[1])]++
поправил. тесты прошли.

2021-04-20 11:19 UTC, agneum approved these changes

2021-04-28 11:36 UTC, merged